### ISSUE TITLE
geom_boxplot with stat='identity'

### ISSUE THREAD

**Issue by jmccreight** [has2k1/plotnine#136]
E.g.
https://stackoverflow.com/questions/10628847/geom-boxplot-with-precomputed-values

```
import numpy
import pandas
from plotnine import *

df = None
for tt in range(1,11):
    data = numpy.random.normal(0,1,1000)
    stats = pandas.DataFrame(
        [[numpy.percentile(data, 100),
          numpy.percentile(data, 75),
          numpy.percentile(data, 50),
          numpy.percentile(data, 25),
          numpy.percentile(data, 0),
          tt]],
        columns=['ymax',
                 'upper',
                 'middle',
                 'lower',
                 'ymin',
                 'day']
    )
    if df is None:
        df = stats
    else:
        df = df.append(stats)


ggplot(df,
       aes(x='day',
           ymax='ymax',
           upper='upper',
           middle='middle',
           lower='lower',
           ymin='ymin')
) + \
geom_boxplot(stat='identity')
```

The traceback descends into pandas from this point. 
```
~/anaconda3/lib/python3.6/site-packages/plotnine/geoms/geom_boxplot.py in setup_data(self, data)
     71         # min and max outlier values
     72         omin = [np.min(lst) if len(lst) else +np.inf
---> 73                 for lst in data['outliers']]
     74         omax = [np.max(lst) if len(lst) else -np.inf
     75                 for lst in data['outliers']]
```
I unsuccessfully attempted a hack...

**Comment by jwhendy** [comment]
It looks like `stat_identity.py` expects you to supply pretty much everything, as you've done... with the exception of `outliers`. The failure is because `geom_boxplot.py` expects the data to have an `outliers` column. From looking at `stat_boxplot.py`, which is what I figure `geom_boxplot` expects as the default data format, we see:

```
from matplotlib.cbook import boxplot_stats
res = boxplot_stats(X, whis=params['coef'], labels=labels)[1]
...
d = {'ymin': res['whislo'],
     'lower': res['q1'],
     'middle': [res['med']],
     'upper': res['q3'],
     'ymax': res['whishi'],
     'outliers': [res['fliers']],
     'notchupper': res['med']+1.58*res['iqr']/np.sqrt(n),
     'notchlower': res['med']-1.58*res['iqr']/np.sqrt(n),
     'x': x,
     'width': width,
     'relvarwidth': np.sqrt(n)}
 return pd.DataFrame(d)
```

From fiddling around and having `stat_boxplot.py` print our `res`, `boxplot_stats()` returns a dictionary per group with a `fliers` key having a an `np.array()` for the value. This is what gets extracted in the function above and returned as a column in the data frame.

The short story is, it looks like to manually specify the required aesthetics for a boxplot by using `stat_identity`, you have to supply your outliers manually as well.
```
df = None
for tt in range(1,11):
    data = numpy.random.normal(0,1,1000)
    stats = pandas.DataFrame(
        [[numpy.percentile(data, 100),
          numpy.percentile(data, 75),
          numpy.percentile(data, 50),
          numpy.percentile(data, 25),
          numpy.percentile(data, 0),
          tt,
          np.array([])]],
        columns=['ymax',
                 'upper',
                 'middle',
                 'lower',
                 'ymin',
                 'day',
                 'outliers']
    )
    if df is None:
        df = stats
    else:
        df = df.append(stats)
```
![2018-05-05_121435](https://user-images.githubusercontent.com/379357/39665714-e6331368-505d-11e8-96aa-7281ae822a30.png)

Whether or not this is a bug will be up to @has2k1 . I'm inclined to think it isn't... `stat_identity` expects you to supply everything needed to construct the boxplot, and `outliers` is one of those items.

Hope that helps!

**Comment by has2k1** [comment]
@jmccreight, has supplied all the required aesthetics and the `geom` is failing, technically that is a bug.
