### ISSUE TITLE
Too few colors?

### ISSUE THREAD

**Issue by SkBlaz** [has2k1/plotnine#146]
Dear authors, I am currently getting this error:

/home/user/miniconda3/lib/python3.6/site-packages/mizani/palettes.py:679: UserWarning: Palette can return a maximum of 13 values. 14 were requested from it.

when trying to plot some basic scatterplots. What would be the fix for this?

**Comment by has2k1** [comment]
As the error indicates, the default colour palette has less colours than your data is requesting from it.
You need to change select a different palette using any of the discrete colour scales.

**Comment by haematologic** [comment]
@SkBlaz I also experienced this recently and tried the solution above then realised it was due to too few shapes available rather than colours in the default palette.

To resolve this I created a custom shape scale - see  [http://plotnine.readthedocs.io/en/stable/_modules/plotnine/scales/scale_shape.html](http://plotnine.readthedocs.io/en/stable/_modules/plotnine/scales/scale_shape.html)



```
from plotnine import scale_shape
from mizani.palettes import manual_pal


def scale_shape_Publication(**kwargs):
    return scale_shape(palette=manual_pal([
    
    # Filled
    'o',  # circle
    '^',  # triangle up
    's',  # square
    'D',  # Diamond
    'v',  # triangle down
    '*',  # star
    'p',  # pentagon
    '8',  # octagon
    '<',  # triangle left
    'h',  # hexagon1
    '>',  # triangle right
    'H',  # hexagon1
    'd',  # thin diamond
    
    # Unfilled
    '+',  # plus
    'x',  # x
    '.',  # point
    '1',  # tri_down
    '2',  # tri_up
    '3',  # tri_left
    '4',  # tri_right
    ',',  # pixel
    '_',  # hline
    '|',  # vline
    1,    # tickleft
    2,    # tickright
    3,    # tickup
    4,    # tickdown

    ]), **kwargs)
```

**Comment by SkBlaz** [comment]
Thanks, this works too!
