### ISSUE TITLE
Preferred Citation?

### ISSUE THREAD

**Issue by ejolly** [has2k1/plotnine#160]
I've utilized plotnine to visualize some of my own work and am in the processing of submitting a manuscript. I'd like to acknowledge the package and development with a citation. Do you have a preferred citation I should use (e.g. DOI or the github page)? For example I've used the following two in the past to cite [ggplot](https://cran.r-project.org/web/packages/ggplot2/citation.html) and [seaborn](https://zenodo.org/record/12710) respectively.

**Comment by has2k1** [comment]
I thought I had a DOI with zenodo for plotnine, it turns out I do not. I am prepping for a release by end of the week. That should have a DOI. Thank you for the reminder.

On the other hand, if you have made heavy use of the scaling library [mizani](https://github.com/has2k1/mizani), it has a [DOI](https://zenodo.org/record/1204282)

**Comment by has2k1** [comment]
I have added a zenodo DOI. See the [readme](https://github.com/has2k1/plotnine).
