### ISSUE TITLE
Legend clipping - no rescaling with tight layout

### ISSUE THREAD

**Issue by physici** [has2k1/plotnine#186]
Hi,

first: Great Work 👍 

When plotting data with a lot of different categories - 33 in my use case - the legend gets created with multiple columns/rows. In many cases it gets clipped at the right border of the image. Normaly, in maptlotlib, you can adjust the scaling by using tight_layout. But this is not working with a ggplot graph. So I have no way to get a correct legend, except scaling the window by hand during creation.

Minimum example:
import pandas as pd
import numpy as np
from plotnine import *

labels = ['label {}'.format(x) for x in range(33)]
test = np.random.rand(33, 2)
df = pd.DataFrame(test, columns=['foo', 'bar'], index=labels)
df.reset_index(inplace=True)
(ggplot(df) + aes(x='foo', y='bar', color='index') + geom_point())

Is there a chance to solve that?

Thanks,
Rainer

**Comment by has2k1** [comment]
It is not a bug. This is a know limitation due to how matplotlib layout the plot components.

You can solve it using the `subplots_adjust` themeable to make space for the large legend. e.g.

```python
+ theme(subplots_adjust={'right': 0.85})`
```
That means that the legends takes about 15% of the horizontal plot space. And, if you need to you can also adjust the [figure_size](https://plotnine.readthedocs.io/en/stable/generated/plotnine.themes.themeable.figure_size.html).
