### ISSUE TITLE
how to print percentage of count per bar ?

### ISSUE THREAD

**Issue by Fandekasp** [has2k1/plotnine#231]
Hi,
I've just started learning how to use plotnine, but the lack of examples in the documentation makes it really hard to understand how to use each function.

In this case, I'd like to print the number of items and the percentage of items in each bar.

![](https://i.imgur.com/0VbMWGD.png)

It took me a while to figure out the `aes(label='stat(count)')` trick in geom_text to print the count, but I can't get the percentage printed out.
I cannot find a percent method in stats or scales. Any idea how to get this done ?

Also, I was trying to figure out how to replace my x axis labels (False, True) with better names (sincere, insincere), but I couldn't get it either. the xlab only sets a global label for the y axis. Any help on this would also be greatly appreciated.

Cordially

**Comment by has2k1** [comment]
Here is one option

```python
from plotnine import *
from plotnine.data import *

def func(counts, percentages):
    return [f'{c} ({p}%) 'for c, p in zip(counts, percentages)]

(ggplot(mtcars, aes('factor(cyl)', fill='factor(cyl)'))
 + geom_bar()
 + geom_text(
     aes(label='stat(func(count, 100*prop))', colour='factor(cyl)', group=1),
     stat='count',
     nudge_y=0.5,
 )
)
```
![stat_count_percentages](https://user-images.githubusercontent.com/780341/48696352-c1276e80-ebf2-11e8-8c51-a636fbbc710b.png)

You can also get the same result with two `geom_text` geoms. Next time please post a working minimal  example of what you are trying to do.

**Comment by Fandekasp** [comment]
Thanks @has2k1. Do you also have a tip for a good resource to study so that I can figure out this kind of thing on my own next time ?

**Comment by has2k1** [comment]
plotnine has pretty much the same API as ggplot2, so most ggplot2 resources would be helpful. However, this particular issue is tricky and I expect most users to struggle with it because:

1. You needed to combine two computed aesthetics in a formula.
2. The need to override the computed groups.

In the first case, it is just knowing that the flexibility is available, I think the documentation for `aes` does not emphasise it enough. The second case is tricky and covered in [a tutorial](https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-automatic-grouping-insufficient.html).

When I encounter an issue like this, I make a note of it and put it in the [miscellaneous](https://plotnine.readthedocs.io/en/stable/tutorials.html#miscellaneous section of the tutorials. That is the place for the little things that users may struggle with, I will put one for this issue to.
