### ISSUE TITLE
Ribbon Plots don't seem to work with faceting

### ISSUE THREAD

**Issue by cpennington** [has2k1/plotnine#26]
I haven't really been able to figure out why, but the fill in ribbon plots in faceted charts doesn't seem to work.

**Comment by has2k1** [comment]
Please provide an example. Thanks.

**Comment by cpennington** [comment]
Yeah, I haven't been able to boil down my particular application into a test-case that show's the failure, yet. Will do, though.

**Comment by has2k1** [comment]
This modified example from the tests brings up a similar issue

```python
n = 4            # No. of ribbions in a vertical stack
m = 10          # Points
width = 2*np.pi  # width of each ribbon
x = np.linspace(0, width, m)

df = pd.DataFrame({
        'x': np.tile(x, n),
        'ymin': np.hstack([np.sin(x)+2*i for i in range(n)]),
        'ymax': np.hstack([np.sin(x)+2*i+1 for i in range(n)]),
        'z': np.repeat(range(n), m)

    })

(ggplot(df, aes('x',ymin='ymin', ymax='ymax',
                    fill='factor(z)'))
 + geom_ribbon()
 + facet_wrap('~ z')
```

Problem is caused by https://github.com/pandas-dev/pandas/issues/16793 at https://github.com/has2k1/plotnine/blob/164003d844438d8255f576448cb7bff92e81f96d/plotnine/facets/facet_wrap.py#L146. 
https://github.com/has2k1/plotnine/blob/164003d844438d8255f576448cb7bff92e81f96d/plotnine/facets/facet_grid.py#L153 must also be affected.

**Comment by cpennington** [comment]
Thanks for digging in to the issue. I wonder if we could fix it by explicitly sorting by `ts`? I tried that from the outside, but it didn't work.

**Comment by has2k1** [comment]
I have a fix lined up.
