### ISSUE TITLE
Add `interaction` function

### ISSUE THREAD

**Issue by ynadji** [has2k1/plotnine#345]
[ggplot in R](https://stackoverflow.com/questions/18598953/geom-line-connects-points-mapped-to-different-groups) has a function called `interaction` that makes it easy to `group` plots on the combination of two columns without having to create a new column. For example, the following code snippet I just wrote:

```python
df = ...
df['group'] = df.domain_levels.astype('str') + '-' + df.rcode_name.astype('str')
p = ggplot(tmp, aes(x='ts_by_hour',
                    y='count',
                    group='group',
                    color='domain_levels',
                    shape='rcode_name'))
```

could instead be written

```python
df = ...
p = ggplot(tmp, aes(x='ts_by_hour',
                    y='count',
                    group=interaction('domain_levels', 'rcode_name'),
                    color='domain_levels',
                    shape='rcode_name'))
```

Apologies if this is included under another name! I only searched for `interaction` in the repo. It's a pretty minor improvement, but I'm hoping that means it's also simple to do :).

Thanks for `plotnine`!

**Comment by has2k1** [comment]
`interaction` is a function in base `R` and it is not as commonly used in ggplot2 code (`factor` is common) so we cannot justify an exception for it. Such manipulation functionality needs to somewhere else where it fits in.

On the other hand, the [forcats](https://github.com/tidyverse/forcats) has a similar function called [fct_cross](https://forcats.tidyverse.org/reference/fct_cross.html). For my package [plydata](https://github.com/has2k1/plydata) a take of dplyr, the next version will have tools to manipulate categoricals (mimicing the forcats package). In there is a function (`cat_zip`[1] IIRC, already written) that does exactly this.
 
I am already thinking about making plotnine more aware of plydata so that you would be able to write

```python
aes(group=cat_zip('domain_levels', 'rcode_name'))
```
and not have to create a new column.

I think for your example you can do

```python
p = ggplot(tmp, aes(x='ts_by_hour',
                    y='count',,
                    color='domain_levels',
                    shape='rcode_name'
                    ),
                    group=list(zip(tmp.domain_levels, tmp.rcode_name)) # does this work?
)

```

[1] In python terminology, interaction is zipping!

**Comment by ynadji** [comment]
Worked perfectly! Thanks for the super prompt reply @has2k1. Again, thanks for the wonderful lib.
