### ISSUE TITLE
Reinstalling existing packages with the same version on install

### ISSUE THREAD

**Issue by gareth-harman** [has2k1/plotnine#366]
Installation via pip on macOS uninstalled and reinstalled scipy, matplotlib, and numpy with the same version that was already installed.

**Comment by has2k1** [comment]
That should not happen, I doubt the issue is with plotnine. There are more [required packages](https://github.com/has2k1/plotnine/blob/82d2421f4c048a7ebf98439b55b5929134a19b1f/setup.py#L51-L60) than those three.

If you uninstall plotnine and reinstall it, are the same packages reinstalled? What about if you install matplotlib?
