### ISSUE TITLE
geom_smooth messes up groupings for numeric columns

### ISSUE THREAD

**Issue by iosband** [has2k1/plotnine#39]
I've run into some issues with smoothing over data with numeric columns for colors.

Smoothing (and potentially other methods) seem to run into problems related to DISCRETE_COLUMNS.
I've attached a small notebook printout detailing the failure case.

[plotnine_group_smooth.pdf](https://github.com/has2k1/plotnine/files/1166347/plotnine_group_smooth.pdf)

**Comment by iosband** [comment]
I've noticed there's a mistake in that notebook, missing an initialization for `scale=1` in the second box... but hopefully the bug makes sense 👍

**Comment by has2k1** [comment]
That is not a bug. By default, integer columns are not treated as discrete. Discreteness is determined by the `dtype` of the column. If you want an integer column to be treated as discrete, you can turn it into a categorical with `'factor(col)'`.

```python
# However, things mess up with numerical values instead of strings
df['alg_num'] = df.alg.astype('category').cat.codes.values
df.head()

# Grouping and colours are fine when numbers
p = (gg.ggplot(df)
 + gg.aes('x', 'y', colour='alg_num')
 + gg.geom_line(gg.aes(group='unique_id'), alpha=0.5))
p
```

There is no grouping on the colour variable. It only appears so because there are *only two values* on the scale.

Is it the case that you just want to use viridis colours instead?
