### ISSUE TITLE
Boxplots don't get drawn properly when there are zeros and it is log transformed

### ISSUE THREAD

**Issue by ctSkennerton** [has2k1/plotnine#40]
I came across an issue where some parts of the box plot don't get drawn when I log transform data that had a lot of zeroes in it. The image below illustrates what I mean. Having a quick look at the code I can see that `cbook.boxplot_stats` is returning `-inf` for some things like IQR or min values which I guess is causing weirdness. 

```python
import pandas as pd
from plotnine import *

reprex = pd.DataFrame({'value': [0,0,1,5,100000,4739273,11,0.0001,0, 0.00001,0.00001,1,5,100000,4739273,11,0.0001,0.00001], 
                       'cat':['1','1','1','1','1','1','1','1','1','2','2','2','2','2','2','2','2','2']})
ggplot(reprex, aes('cat', 'value')) + scale_y_log10() + geom_boxplot()
```
![image](https://user-images.githubusercontent.com/685235/28594316-5fe355b4-7144-11e7-9cb3-3b308062864f.png)

**Comment by has2k1** [comment]
I think you should get a warning about divide by zero operations. If that is the case then the problematic plot should not be a surprise, after-all `log(0)` is infinite.

However since visualisation is essentially an imprecise representation of data, for your case you can exploit this fact to obtain an interpretation of the data that is visually accurate with something like.

```python
epsilon = np.finfo(float).eps
ggplot(reprex, aes('cat', 'value+epsilon')) + scale_y_log10() + geom_boxplot()
```

That should prevent the `log(0)` operations.

**Comment by ctSkennerton** [comment]
Thanks for the solution. I think I was more surprised, coming from ggplot2, where this seems to be handled internally.

**Comment by has2k1** [comment]
Well, I guess we could handle it too.
