### ISSUE TITLE
Doesn't work if the plot is not the last thing in the cell

### ISSUE THREAD

**Issue by impact27** [has2k1/plotnine#428]
If I run:
```python
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
from plotnine.data import mtcars

(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
+ geom_point()
+ stat_smooth(method='lm')
+ facet_wrap('~gear'))

a = 1 + 1
```
in a jupyter notebook, the plot won't be shown. It only works if the plot is at the end of the expression. 
This causes issue https://github.com/spyder-ide/spyder/issues/13464

**Comment by has2k1** [comment]
Jupyter notebook automatically prints the last object cell and in plotnine the plot drawn by printing the ggplot object. So to get automatic plotting the ggplot object has to be the last object in the cell. Otherwise you have to explicitly print it.

```python
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
from plotnine.data import mtcars

p = (ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear')
)

print(p) 

a = 1 + 1
```

Jupyter treats matplotlib with preference way by printing any figures created in the cell. If you want plotnine to leverage that preference, then you need to explicitly draw the plot which creates a matplotlib figure in the background is noticed by jupyter.

```python
(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear')
).draw()

a = 1 + 1
```

It is better to print the object.

**Comment by rhalbersma** [comment]
I would be nice if ggplot objects had a `__str__` method that draws the plot without the `<ggplot:hash>` annotation. For pretty printing, users could then write `print(p)` and for debugging `print(repr(p))` would still be available.

**Comment by has2k1** [comment]
@rhalbersma, please submit a separate issue.
