### ISSUE TITLE
Is it possible to control the output figure size including legends and axes?

### ISSUE THREAD

**Issue by haggaie** [has2k1/plotnine#481]
When I set `figure_size` through theme or the options it seems like this setting only controls the figure itself, but does not take into account legends, axis, titles, etc.

Is there another setting that could set the size of the overall resulting figure?

**Comment by has2k1** [comment]
It is not possible. The backend (Matplotlib) cannot guarantee that.

**Comment by haggaie** [comment]
Too bad. Thanks for the quick answer.

**Comment by himalayajung** [comment]
@haggaie Maybe you can use base_size. e.g. theme_grey(base_size=20)

**Comment by haggaie** [comment]
Thanks @himalayajung, though I don't think that would help. What I want to accomplish it to set the size of the pdf plotnine would generate in advance, and have all the components fit that space. That makes it easier to them include the figure in a paper and keeping font and figure sizes uniform. I believe this is similar to the matplotlib tight layout feature, though I haven't used it in a while, so I might be mistaken.

**Comment by benjaminleroy** [comment]
Hi there, I know this issue is a year old, but  @wangmallory and I have been working on an extension to `plotnine` ([`cowpatch`](https://benjaminleroy.github.io/cowpatch/)), and in this package we use an idea suggested in [a blog post by Kavi Gupta](https://kavigupta.org/2019/05/18/Setting-the-size-of-figures-in-matplotlib/) in a backend to create correctly sized `plotnine` objects / `matplotlib` figures.   The problem (love `plotnine` b.t.w.) is that `plotnine`'s underlying code leverages `bbox_inches=“tight”` from `matplotlib`. I do see that @has2k1 is looking into converting to `plt.tight_layout()` (issue #390).

A solution using our package would be something like the following:

```python
import plotnine as p9
import cowpatch as cow 

# for reproducible example:
import plotnine.data as p9_data
g0 = p9.ggplot(p9_data.mpg) +\
    p9.geom_bar(p9.aes(x="hwy")) +\
    p9.labs(title = 'Plot 0')

out_info = cow.svg_utils._select_correcting_size_svg(g0, height = 4, width = 5, dpi = 96) #height and width in inches (in this example keep dpi = 96 )

# feed out_info[0], out_info[1] into p9.save’s height and width parameter
g0.save(filename = “local_image.pdf”, width = out_info[0], height = out_info[1])
```

The resulting file `local_image.pdf` (in whatever format you'd like) should be the desired size (up to some `eps`). For the above example, here is a screengrab of the size information from adobe acrobat:

<img width="589" alt="Screen Shot 2022-04-10 at 10 10 31 AM" src="https://user-images.githubusercontent.com/8593016/162631251-765d3480-d451-4427-ba9b-1ed6ea7d3269.png">

**Note** that this “solution” is an interative one, and sometimes (especially with large legends) this can still fail since the legend may constraint the minimum size your image can actually take.
