### ISSUE TITLE
Extract matplotlib axes from plotnine plots

### ISSUE THREAD

**Issue by shoyer** [has2k1/plotnine#63]
Seaborn has the nice feature that you can extra matplotlib `Axis` objects from a `FacetGrid`, which allows you to make low-level adjustments in matplotlib if necessary.

Is something like this possible in plotnine?

**Comment by has2k1** [comment]
It is possible. If you manually the `ggplot.draw` method, it returns the matplotlib figure; you then get the list of `axes`; then `spine` or `Axis`; and so on. e.g.

```python
p = ggplot() + ...
fig = p.draw()
axs = fig.get_axes()
for ax in axes:
    ax.spine['top'].set(...)
    xaxis = ax.get_xaxis()
```

**Comment by shoyer** [comment]
Awesome, thank you. This is a very handy escape hatch.

**Comment by has2k1** [comment]
Out of curiosity, what adjustments can you not make with the theme system? Is it to style `axis`s' on separate panels differently?

**Comment by shoyer** [comment]
One of my colleagues wanted to overlay plots with a secondary set of axes, and it seemed like that couldn't be done directly in plotnine.

**Comment by has2k1** [comment]
When Matplotlib ships the constraint layout manager, I'll look into adding secondary axes functionality.

**Comment by maddytae** [comment]
If I understand correctly, it does not pass the fig to matplotlib but rather redraws the figure on matplotlib. Which is perhaps the reason why I can not set_ylabel as blank and then put new y axis label. 

fig = plot.draw()
axs = fig.get_axes()
for ax in axs:
    ax.set_ylabel('')
    ax.set_ylabel('New Y-axis Title')
    xaxis = ax.get_xaxis()

fig

Is it possible to get the matplotlib fig object with all attributes rather than a picture drawn upon matplotlib?
