### ISSUE TITLE
geom_abline() fails when using aes with a color if the color is not a list

### ISSUE THREAD

**Issue by JenniferHem** [has2k1/plotnine#671]
I wanted to produce a named line in one of my plots. However when geom_abline receives aes() containing a color, it fails with the error: PlotnineError: "Could not evaluate the 'color' mapping: 'blue' (original error: name 'blue' is not defined)"

```
(
    ggplot(mpg, aes(x='displ', y='hwy'))
    + geom_point()
    + geom_abline(aes(intercept=45,slope=-5, color = "blue"))

)
```
Fails with Error.

```
(
    ggplot(mpg, aes(x='displ', y='hwy'))
    + geom_point()
    + geom_abline(aes(intercept=45,slope=-5, color = ["blue"]))

)
```
Gives the plot as expected:
![image](https://user-images.githubusercontent.com/68546404/222105693-ca64ce9f-a6f3-4bea-a25e-fda45ac66725.png)

Not sure if this is intended. If so, mentioninig it in the docs would be great!

**Comment by has2k1** [comment]
As you want a direct assignment, you need to assign to `color` outside of `aes()`, otherwise `aes(color="blue")` does not refer to any variable. Contrast that with `aes(color="'blue'")` which is evaluated to the string "blue", and in this context it is the same as `aes(color=["blue"]`)!

```python
(
 ggplot(mpg, aes(x='displ', y='hwy'))
 + geom_point()
 + geom_abline(aes(intercept=45, slope=-5), color="blue")
)
```

See the documentation for [aes](https://plotnine.readthedocs.io/en/stable/generated/plotnine.mapping.aes.html#plotnine.mapping.aes).
