### ISSUE TITLE
`geom_smooth` doesn't apply `alpha`

### ISSUE THREAD

**Issue by david-cortes** [has2k1/plotnine#770]
Passing argument `alpha` to `geom_smooth` doesn't end up applying transparency.

Example:
```python
import numpy as np, pandas as pd, plotnine as p9
df = pd.DataFrame({
    "x": np.arange(100),
    "y" : np.arange(100) * np.random.random(size=100)
})
print(
    p9.ggplot(df, p9.aes(x="x", y="y"))
    + p9.geom_point(alpha=0.1)
    + p9.geom_smooth(alpha=0.1)
)
```
![image](https://github.com/has2k1/plotnine/assets/11860098/d50d3574-cdfa-4ce4-8f91-f95da0494c98)

**Comment by has2k1** [comment]
For `geom_smooth` the `alpha` aesthetic only applies to the confidence interval because commonly, you only want to see through that area and not the line.

You can set the colour of the line to rgba hex value e.g. `color="#00000077"` to get a transparent line.

Or, if you are mapping the color to a variable, you use staged evaluation to modify the color from rgb to rgba i.e. 

```python
aes(color=stage("col1", after_scale="make_transparent(color)"))
```

where

```python
def make_transparent(rgb_seq):
    return [f"{c}77" for c in rgb_seq]
```
