### ISSUE TITLE
Specifying dpi option in theme does not work in quarto

### ISSUE THREAD

**Issue by machow** [has2k1/plotnine#773]
When using quarto with a qmd, setting the `theme(dpi=...)` option does not seem to affect plot output.

**example.qmd**

``````python
---
format:
    html:
       # setting fig-dpi does affect DPI
       # fig-dpi: 400
       fig-dpi: 100
---

```{python}
from plotnine import *
import pandas as pd

df = pd.DataFrame({"x": [1,2,3], "y": [4,5,6]})
```

```{python}
ggplot(df, aes("x", "y")) + geom_point()
```

```{python}
ggplot(df, aes("x", "y")) + geom_point() + theme(figure_size=(6, 4), dpi = 400)
```


``````

Both plots produced for me are around 8kb, and about 600 x 400px. Note that leaving out the `fig-dpi` option completely in the top-matter results in a DPI setting of 100 (or similar) in the rcParams.

### Possible causes

Pieces I noticed digging around:

* quarto sets [a number of matplotlib settings](https://github.com/quarto-dev/quarto-cli/blob/1ec01151ad59930b6042abed34ee9f90fd1826ab/src/resources/jupyter/lang/python/setup.py#L19-L26) before running python qmds
* uncommenting the `fig-dpi` in the yaml topmatter of the example will affect plots. (and it's set via code in point above).
* when run in a jupyterlab notebook, setting `theme(dpi=...)` worked fine

cc @cscheid, in case there's another important quarto piece I'm missing?! I'm a bit stumped here 😓

**Comment by cscheid** [comment]
@machow You found the only thing I'm aware of, that the format `fig-dpi` setting is forwarded to rcParams exactly where you've highlighted it.

**Comment by has2k1** [comment]
I have fixed this. Though it is worth noting that the combination of `savefig.dpi` and `figure.dpi` parameters is [https://github.com/matplotlib/matplotlib/issues/24644](delicate), preferably only `figure.dpi` should be set.

https://github.com/quarto-dev/quarto-cli/issues/9470 is related to this in that we are still unable to get the expected display size.

**Comment by cscheid** [comment]
(I'm just piping in to say I love the `issue` shortcode for the changelog, and we might end up adopting something like that in quarto-cli ourselves!)

**Comment by has2k1** [comment]
`savefig.dpi` is less used and usually users only set `figure.dpi` and want the same value for both cases. The way to express that intention without values going out-of-sync is by setting the `savefig.dpi` to the string `"figure"`.

```python
 plt.rcParams['figure.dpi'] = fig_dpi
 plt.rcParams['savefig.dpi'] = "figure"
```

This way `savefig.dpi` will never go out-of-sync, unless the user knows what they are doing. It easily goes out-of-sync because the `dpi` of the figure can be altered (`fig.set_dpi(42)` or by saving the figure in a different rcParams context after it has been created!).

Using `"figure"` for `savefig.dpi` is how matplotlib decided to implement the "one source of truth", made it the [default](https://matplotlib.org/stable/users/explain/customizing.html) setting and therefore you can omit it.
