### ISSUE TITLE
documentation: plotnine histogram how to show price ranges, not counts

### ISSUE THREAD

**Issue by jrbrearley** [has2k1/plotnine#93]
I am wondering if there is a way to get geom_histogram to show price ranges for the data in the data/diamonds.csv? I can get it to show counts based on cut and clarity, but not price ranges. For reference, I have attached my sample code.

The more I think about this, the more I am thinking that this type of analysis might be outside the scope of a plotting routine. When you have ranges of data that overlap for a given category, in the diamonds case that being the cut, there would need to be some kind of possibly weighted average to determine the price range boundaries. To make the plot useful to a end consumer / shopper, the price ranges within each stacked column would need to arranged with most expensive on top.
[plotnine_diamonds.zip](https://github.com/has2k1/plotnine/files/1510808/plotnine_diamonds.zip)

**Comment by jrbrearley** [comment]
![ggplot_idea](https://user-images.githubusercontent.com/32575796/33344670-c7c2f196-d457-11e7-8c57-0a99bbe9dd5a.png)

In the above plot, the y-scale is a bit off, should be up to $20,000. Each segment of the stacked column should be proportional to the range of cut prices. More expensive diamonds at top of column.

Lets say you were getting married and wanted to know what a diamond ring costs, based on clarity and cut. This plot would show you ranges of prices you would expect to pay.

If the plot only showed counts on the y-scale, that would represent availability of diamonds, probably not much interest to someone that wants a ring fairly soon. 

BTW, this plot was generated with the year old release of ggplot, which has many known issues.

**Comment by has2k1** [comment]
```python
from plotnine import *
from plydata import *
from plotnine.data import diamonds
```

> Lets say you were getting married and wanted to know what a diamond ring costs, based on clarity and cut. This plot would show you ranges of prices you would expect to pay.


1.

```python
df = (
    diamonds
    >> group_by('clarity', 'cut')
    >> summarize(min_price='min(price)', mean_price='mean(price)', max_price='max(price)')
)

(ggplot(df)
 + geom_col(aes('clarity', 'mean_price', fill='cut'), position='dodge')
 + geom_linerange(aes('clarity', ymin='min_price', ymax='max_price', color='cut'), size=1, position=position_dodge(width=0.9))
 + scale_color_hue(l=.3)
 + theme(figure_size=(11, 8))
)
```
![mean_min_max_plydata](https://user-images.githubusercontent.com/780341/33350887-bc55ddf0-d466-11e7-968a-3f7624baad68.png)

2.
```python
(ggplot(diamonds)
 + stat_summary(aes('clarity', 'price', fill='cut'), fun_y=np.mean, geom='col', position='dodge')
 + stat_summary(aes('clarity', 'price', color='cut'), fun_ymin=np.min, fun_ymax=np.max, geom='linerange', size=1, position=position_dodge(width=0.9))
 + scale_color_hue(l=.3)
 + theme(figure_size=(11, 8))
)
```
![mean_min_max](https://user-images.githubusercontent.com/780341/33350907-d5ebee4e-d466-11e7-9a3b-2aae518e5c4d.png)

3.
```python
(ggplot(diamonds)
 + stat_summary(aes('clarity', 'price', fill='cut'), geom='col', position='dodge')
 + stat_summary(aes('clarity', 'price', color='cut'), geom='linerange', size=1, position=position_dodge(width=0.9))
 + scale_color_hue(l=.3)
 + theme(figure_size=(11, 8))
)
```
![bootstrap_mean_min_max](https://user-images.githubusercontent.com/780341/33350919-ea51d36c-d466-11e7-880e-8862b236b03c.png)

1 and 2 yield the same plot. With 1 you do the data manipulation explicitly, but you do not have to since the manipulation consists of creating summary statistics -- there is a `stat` for that. 2, uses the correct `stat` and `geom` combinations to summarise and visualise the data. 3 is just like 2, but the summary statistics are bootstrapped (this is the default), so the effect of *outliers* is minimised.

I think you can create a better plot without the bars, maybe using `geom_point` and `geom_errorbar`.
